### ISSUE TITLE
Passing spark-defaults.conf values as part of spring cloud task modules

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-task-app-starters#18]
_From @rejurs on April 29, 2016 20:9_

Hi Team,

Could you please help me to pass the spark-defaults.conf values when we are running **java -jar sparkapp-yarn/target/sparkapp-yarn-task-1.0.0.BUILD-SNAPSHOT-exec.jar**. 

_Copied from original issue: spring-cloud/spring-cloud-task-modules#36_

**Comment by rejurs** [comment]
@sabbyanandan : Is this resolved? / Is there any timeline ? / Ami I making any mistake? Could you please update me.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-task-app-starters/spark-yarn#1
