### ISSUE TITLE
Integ test failures in spring-cloud-starter-task-sqoop-tool

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-task-app-starters#24]
All the integ tests in SqoopToolTaskApplicationTests are ignored due to some issues (non-zero return code in sqoop job execution). All the tests in spring-cloud-starter-task-sqoop-job are passing however.

**Comment by trisberg** [comment]
Removed @Ignore from SqoopToolTaskApplicationTests and tests pass  https://build.spring.io/browse/SCT-SCTAS-44/test

Not sure what the issue was.
