### ISSUE TITLE
Can anyone provide the documentation for spark yarn cluster task?

### ISSUE THREAD

**Issue by sandip0018** [spring-cloud/spring-cloud-task-app-starters#33]
Hi @sabbyanandan ,

can you please provide the link on how we can use spark yan cluster task ?, what are the required dependency?, i want to run it from local as well as from cloud foundry.

Thanks,
Sandip

**Comment by sabbyanandan** [comment]
@trisberg recently created a [sample](https://gist.github.com/trisberg/79d50dc46c11c0fb7020c8ccc72d1234#running-a-spark-application-on-yarn-using-spring-cloud-data-flow) for `spark-yarn` application running in SCDF's YARN implementation. If you've other examples from your experiments, please feel free to contribute as PR in [samples repo](https://github.com/spring-cloud/spring-cloud-dataflow-samples).

> i want to run it from local as well as from cloud foundry

FYI: Task API support in PCF is currently at alpha release (_aka: experimental_) and we are actively working to build integration with the experimental APIs.
