### ISSUE TITLE
Make it easier to extend Spark app starters 

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-task-app-starters#57]
To be able to extend the spark app starers we need to add protected methods in the command line runner implementation for :
- creating the SparkContext
- adding Spark properties and client submit args
- configuring the Spark Client

**Comment by fmarchand** [comment]
I would like to know if you advanced on that part. I need to pass configuration properties to my Spark Task and according to the `SparkClusterTaskConfiguration` only spark options in `SparkClusterTaskProperties` are passed to the spark job. Is there another way to do that ?

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-task-app-starters/spark-client#1
